// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyByF7NAkigP5JgoHFKj67T3sfK0t3ynj_0',
    appId: '1:196597269676:web:e601b86b7dcce1383acb09',
    messagingSenderId: '196597269676',
    projectId: 'oncoposts',
    authDomain: 'oncoposts.firebaseapp.com',
    storageBucket: 'oncoposts.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCxGElMGUHz_4h1iR6fIX6KZfdRKXAlrCw',
    appId: '1:196597269676:android:ce4175df4ed8a2a63acb09',
    messagingSenderId: '196597269676',
    projectId: 'oncoposts',
    storageBucket: 'oncoposts.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCQgQ5Fi6EG2hkr2_rlfPXRpjpfT_ZOMOg',
    appId: '1:196597269676:ios:a9314a6e07f72f933acb09',
    messagingSenderId: '196597269676',
    projectId: 'oncoposts',
    storageBucket: 'oncoposts.firebasestorage.app',
    iosBundleId: 'com.firebaseCommentsandLikes.flutterfirebaseposts',
  );

}